// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace IncidentAPI.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Incident
    {
        /// <summary>
        /// Initializes a new instance of the Incident class.
        /// </summary>
        public Incident() { }

        /// <summary>
        /// Initializes a new instance of the Incident class.
        /// </summary>
        public Incident(string id = default(string), string description = default(string), string street = default(string), string city = default(string), string state = default(string), string zipCode = default(string), string firstName = default(string), string lastName = default(string), string phoneNumber = default(string), string outageType = default(string), bool? isEmergency = default(bool?), bool? resolved = default(bool?), string imageUri = default(string), string thumbnailUri = default(string), DateTime? created = default(DateTime?), DateTime? lastModified = default(DateTime?), string sortKey = default(string), string tags = default(string))
        {
            Id = id;
            Description = description;
            Street = street;
            City = city;
            State = state;
            ZipCode = zipCode;
            FirstName = firstName;
            LastName = lastName;
            PhoneNumber = phoneNumber;
            OutageType = outageType;
            IsEmergency = isEmergency;
            Resolved = resolved;
            ImageUri = imageUri;
            ThumbnailUri = thumbnailUri;
            Created = created;
            LastModified = lastModified;
            SortKey = sortKey;
            Tags = tags;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Street")]
        public string Street { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "City")]
        public string City { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "State")]
        public string State { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ZipCode")]
        public string ZipCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FirstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LastName")]
        public string LastName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PhoneNumber")]
        public string PhoneNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OutageType")]
        public string OutageType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsEmergency")]
        public bool? IsEmergency { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Resolved")]
        public bool? Resolved { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ImageUri")]
        public string ImageUri { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ThumbnailUri")]
        public string ThumbnailUri { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Created")]
        public DateTime? Created { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LastModified")]
        public DateTime? LastModified { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SortKey")]
        public string SortKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Tags")]
        public string Tags { get; set; }

    }
}
